# Generated by Django 3.2.16 on 2024-06-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20240621_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('text',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('text',)},
        ),
    ]
