# Generated by Django 3.2.16 on 2024-06-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20240622_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('text',)},
        ),
    ]
